# Generated by Django 5.0.6 on 2024-07-21 08:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Khata', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='khata_transactions',
            name='datetime',
            field=models.DateField(),
        ),
    ]
