# Generated by Django 5.0.6 on 2024-07-21 10:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Khata', '0002_alter_khata_transactions_datetime'),
    ]

    operations = [
        migrations.CreateModel(
            name='given_taken',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('datetime', models.DateField()),
                ('name', models.CharField(max_length=100)),
                ('ammount', models.CharField(max_length=20)),
                ('catagory', models.CharField(max_length=20)),
            ],
        ),
    ]
